// src/components/Layout.tsx
import { Outlet, Navigate } from 'react-router-dom';
import Sidebar from './Sidebar';
import { useStore } from '@/store';

export default function Layout() {
  const isLoggedIn = useStore((s) => s.isLoggedIn);

  if (!isLoggedIn) {
    return <Navigate to="/login" replace />;
  }

  return (
    <div className="flex min-h-screen bg-[#f1f5f9]">
      <Sidebar />
      <main className="flex-1 overflow-auto">
        <div className="p-6 max-w-7xl mx-auto">
          <Outlet />
        </div>
      </main>
    </div>
  );
}

// src/components/Layout.vue
<template>
  <div class="flex min-h-screen bg-[#f1f5f9]">
    <Sidebar />
    <main class="flex-1 overflow-auto">
      <div class="p-6 max-w-7xl mx-auto">
        <router-view />
      </div>
    </main>
  </div>
</template>
<script setup lang="ts">
import { useAppStore } from '@/stores/app'
import { useRouter } from 'vue-router'
import Sidebar from './Sidebar.vue'
const store = useAppStore()
const router = useRouter()
if (!store.isLoggedIn) router.replace('/login')
</script>
