// src/pages/admin/Categories.vue
<template>
  <div class="space-y-6">
    <div class="flex items-center justify-between">
      <div>
        <h1 class="text-2xl font-bold text-gray-900">分类管理</h1>
        <p class="text-gray-500 mt-1">管理课程分类信息</p>
      </div>
      <button @click="showModal = true; editingCat = null; form = { name: '', color: '#3b82f6' }" class="flex items-center gap-2 px-4 py-2.5 bg-blue-500 hover:bg-blue-600 text-white rounded-lg transition-colors text-sm font-medium">
        <Plus class="w-4 h-4" /> 新建分类
      </button>
    </div>

    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
      <div v-for="cat in store.categories" :key="cat.id" class="bg-white rounded-xl border border-gray-100 shadow-sm p-5 hover:shadow-md transition-shadow">
        <div class="flex items-start justify-between mb-3">
          <div :class="`w-10 h-10 rounded-lg flex items-center justify-center`" :style="{ backgroundColor: cat.color }">
            <BookOpen class="w-5 h-5 text-white" />
          </div>
          <button @click="handleEdit(cat)" class="text-xs text-blue-500 hover:underline">编辑</button>
        </div>
        <h3 class="font-semibold text-gray-900">{{ cat.name }}</h3>
        <p class="text-xs text-gray-400 mt-1">{{ store.courses.filter(c => c.categoryId === cat.id).length }} 门课程</p>
      </div>
    </div>

    <Teleport to="body">
      <div v-if="showModal" class="fixed inset-0 z-50 flex items-center justify-center">
        <div class="absolute inset-0 bg-black/50" @click="showModal = false" />
        <div class="relative bg-white rounded-xl shadow-2xl w-full max-w-md mx-4 p-6">
          <h3 class="text-lg font-semibold text-gray-900 mb-4">{{ editingCat ? '编辑分类' : '新建分类' }}</h3>
          <div class="space-y-4">
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-1">分类名称</label>
              <input v-model="form.name" type="text" class="w-full px-3 py-2 rounded-lg border border-gray-200 focus:border-blue-500 outline-none text-sm" />
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-1">颜色</label>
              <div class="flex gap-2">
                <input v-model="form.color" type="color" class="w-10 h-10 rounded cursor-pointer" />
                <span class="text-sm text-gray-500 self-center">{{ form.color }}</span>
              </div>
            </div>
            <div class="flex gap-3 pt-2">
              <button @click="handleSave" class="flex-1 py-2.5 bg-blue-500 hover:bg-blue-600 text-white rounded-lg text-sm font-medium transition-colors">保存</button>
              <button @click="showModal = false" class="flex-1 py-2.5 bg-gray-100 hover:bg-gray-200 text-gray-600 rounded-lg text-sm font-medium transition-colors">取消</button>
            </div>
          </div>
        </div>
      </div>
    </Teleport>
  </div>
</template>
<script setup lang="ts">
import { ref } from 'vue'
import { useAppStore } from '@/stores/app'
import { Plus, BookOpen } from 'lucide-vue-next'

const store = useAppStore()
const showModal = ref(false)
const editingCat = ref<any>(null)
const form = ref({ name: '', color: '#3b82f6' })

const handleEdit = (cat: any) => {
  editingCat.value = cat
  form.value = { name: cat.name, color: cat.color }
  showModal.value = true
}

const handleSave = () => {
  if (editingCat.value) {
    store.updateCategory(editingCat.value.id, { name: form.value.name, color: form.value.color })
  } else {
    store.addCategory({ id: Date.now().toString(), name: form.value.name, color: form.value.color, courseCount: 0 })
  }
  showModal.value = false
}
</script>

// src/pages/admin/Categories.tsx
import { useState } from 'react';
import { useStore } from '@/store';
import { Plus, Edit2, Trash2 } from 'lucide-react';
import Modal from '@/components/Modal';
import type { Category } from '@/types';

const presetColors = ['#3b82f6', '#10b981', '#f59e0b', '#8b5cf6', '#ec4899', '#ef4444', '#14b8a6', '#f97316'];

export default function Categories() {
  const { categories, addCategory, updateCategory, deleteCategory } = useStore();
  const [modalOpen, setModalOpen] = useState(false);
  const [editing, setEditing] = useState<Category | null>(null);

  const openCreate = () => {
    setEditing({ id: `cat-${Date.now()}`, name: '', color: presetColors[0], courseCount: 0 });
    setModalOpen(true);
  };

  const openEdit = (cat: Category) => {
    setEditing({ ...cat });
    setModalOpen(true);
  };

  const handleSave = () => {
    if (!editing) return;
    const exists = categories.find((c) => c.id === editing.id);
    if (exists) {
      updateCategory(editing.id, editing);
    } else {
      addCategory(editing);
    }
    setModalOpen(false);
    setEditing(null);
  };

  const handleDelete = (id: string) => {
    if (window.confirm('确定要删除此分类吗？')) {
      deleteCategory(id);
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">分类管理</h1>
          <p className="text-gray-500 mt-1">管理课程分类</p>
        </div>
        <button onClick={openCreate} className="flex items-center gap-2 px-4 py-2.5 bg-amber-500 hover:bg-amber-600 text-white rounded-lg transition-colors shadow-lg shadow-amber-500/25">
          <Plus className="w-5 h-5" />
          <span>新建分类</span>
        </button>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
        {categories.map((cat) => (
          <div key={cat.id} className="bg-white rounded-xl p-5 border border-gray-100 shadow-sm hover:shadow-md transition-all duration-200">
            <div className="flex items-center gap-3 mb-3">
              <div className="w-10 h-10 rounded-lg flex items-center justify-center" style={{ backgroundColor: cat.color + '20' }}>
                <div className="w-4 h-4 rounded-full" style={{ backgroundColor: cat.color }} />
              </div>
              <div className="flex-1 min-w-0">
                <h3 className="font-semibold text-gray-900 truncate">{cat.name}</h3>
                <p className="text-xs text-gray-500">{cat.courseCount} 门课程</p>
              </div>
            </div>
            <div className="flex gap-2 pt-3 border-t border-gray-50">
              <button onClick={() => openEdit(cat)} className="flex-1 flex items-center justify-center gap-1.5 py-2 text-sm text-gray-600 hover:bg-gray-50 rounded-lg transition-colors">
                <Edit2 className="w-4 h-4" /> 编辑
              </button>
              <button onClick={() => handleDelete(cat.id)} className="flex-1 flex items-center justify-center gap-1.5 py-2 text-sm text-red-500 hover:bg-red-50 rounded-lg transition-colors">
                <Trash2 className="w-4 h-4" /> 删除
              </button>
            </div>
          </div>
        ))}
      </div>

      <Modal isOpen={modalOpen} onClose={() => { setModalOpen(false); setEditing(null); }} title={editing?.id && categories.find((c) => c.id === editing.id) ? '编辑分类' : '新建分类'}>
        {editing && (
          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">分类名称</label>
              <input type="text" value={editing.name} onChange={(e) => setEditing({ ...editing, name: e.target.value })}
                className="w-full px-3 py-2 rounded-lg border border-gray-200 focus:border-amber-500 focus:ring-2 focus:ring-amber-500/20 outline-none text-sm" />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">颜色</label>
              <div className="flex flex-wrap gap-2">
                {presetColors.map((color) => (
                  <button key={color} onClick={() => setEditing({ ...editing, color })}
                    className={`w-8 h-8 rounded-lg transition-transform ${editing.color === color ? 'ring-2 ring-offset-2 ring-amber-500 scale-110' : 'hover:scale-110'}`}
                    style={{ backgroundColor: color }} />
                ))}
              </div>
            </div>
            <div className="flex justify-end gap-3 pt-4 border-t border-gray-100">
              <button onClick={() => { setModalOpen(false); setEditing(null); }}
                className="px-4 py-2 text-sm text-gray-600 hover:bg-gray-100 rounded-lg transition-colors">取消</button>
              <button onClick={handleSave}
                className="px-4 py-2 text-sm bg-amber-500 hover:bg-amber-600 text-white rounded-lg transition-colors">保存</button>
            </div>
          </div>
        )}
      </Modal>
    </div>
  );
}
