// src/pages/admin/Courses.tsx
import { useMemo, useState } from 'react';
import { useStore } from '@/store';
import { Search, BookOpen, Users, TrendingUp, Award } from 'lucide-react';

const getAcademicYear = (dateStr: string) => {
  const date = new Date(dateStr);
  const year = date.getFullYear();
  const month = date.getMonth() + 1;
  return month >= 9 ? `${year}-${year + 1}` : `${year - 1}-${year}`;
};

export default function Courses() {
  const { courses, categories, enrollments, students, teachers, grades } = useStore();
  const [courseNameFilter, setCourseNameFilter] = useState('');
  const [teacherFilter, setTeacherFilter] = useState('');
  const [categoryFilter, setCategoryFilter] = useState('all');
  const [yearFilter, setYearFilter] = useState('all');

  const academicYears = useMemo(() => {
    return Array.from(new Set(courses.map((course) => getAcademicYear(course.createdAt)))).sort();
  }, [courses]);

  const filteredCourses = useMemo(() => {
    return courses
      .filter((course) => course.status === 'active')
      .filter((course) => {
        const teacher = teachers.find((item) => item.name === course.teacher || item.courseIds.includes(course.id));
        const matchCourse = course.title.toLowerCase().includes(courseNameFilter.toLowerCase());
        const matchTeacher = teacherFilter === '' || (teacher?.name || course.teacher).toLowerCase().includes(teacherFilter.toLowerCase());
        const matchCategory = categoryFilter === 'all' || course.categoryId === categoryFilter;
        const matchYear = yearFilter === 'all' || getAcademicYear(course.createdAt) === yearFilter;
        return matchCourse && matchTeacher && matchCategory && matchYear;
      });
  }, [courses, categoryFilter, courseNameFilter, teacherFilter, teachers, yearFilter]);

  const getCategoryName = (id: string) => categories.find((c) => c.id === id)?.name || '未分类';
  const getCategoryColor = (id: string) => categories.find((c) => c.id === id)?.color || '#94a3b8';

  const getCourseStats = (courseId: string) => {
    const courseEnrollments = enrollments.filter((e) => e.courseId === courseId);
    const courseGrades = grades.filter((g) => g.courseId === courseId);
    const avgProgress = courseEnrollments.length > 0
      ? Math.round(courseEnrollments.reduce((sum, e) => sum + e.progress, 0) / courseEnrollments.length)
      : 0;
    const avgScore = courseGrades.length > 0
      ? Math.round(courseGrades.reduce((sum, g) => sum + g.score, 0) / courseGrades.length)
      : 0;
    return {
      studentCount: courseEnrollments.length,
      averageProgress: avgProgress,
      averageScore: avgScore,
      completionCount: courseEnrollments.filter((e) => e.status === 'completed').length,
    };
  };

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-gray-900">课程管理</h1>
        <p className="text-gray-500 mt-1">按学年、课程名和老师名查询已开设课程，查看相关学生学习情况和教师教学情况</p>
      </div>

      <div className="flex flex-wrap gap-4">
        <div className="relative flex-1 min-w-[220px] max-w-sm">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" />
          <input
            type="text"
            value={courseNameFilter}
            onChange={(e) => setCourseNameFilter(e.target.value)}
            placeholder="按课程名查询"
            className="w-full pl-10 pr-4 py-2.5 rounded-lg border border-gray-200 focus:border-amber-500 focus:ring-2 focus:ring-amber-500/20 outline-none text-sm"
          />
        </div>
        <input
          type="text"
          value={teacherFilter}
          onChange={(e) => setTeacherFilter(e.target.value)}
          placeholder="按老师名查询"
          className="px-4 py-2.5 rounded-lg border border-gray-200 focus:border-amber-500 focus:ring-2 focus:ring-amber-500/20 outline-none text-sm min-w-[180px]"
        />
        <select
          value={yearFilter}
          onChange={(e) => setYearFilter(e.target.value)}
          className="px-4 py-2.5 rounded-lg border border-gray-200 focus:border-amber-500 outline-none text-sm bg-white"
        >
          <option value="all">全部学年</option>
          {academicYears.map((year) => <option key={year} value={year}>{year}</option>)}
        </select>
        <select
          value={categoryFilter}
          onChange={(e) => setCategoryFilter(e.target.value)}
          className="px-4 py-2.5 rounded-lg border border-gray-200 focus:border-amber-500 outline-none text-sm bg-white"
        >
          <option value="all">全部分类</option>
          {categories.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}
        </select>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-6">
        {filteredCourses.map((course) => {
          const stats = getCourseStats(course.id);
          const teacher = teachers.find((item) => item.name === course.teacher || item.courseIds.includes(course.id));
          const student = students.find((item) => item.name === course.teacher);

          return (
            <div key={course.id} className="bg-white rounded-xl border border-gray-100 shadow-sm p-5 space-y-4">
              <div className="flex items-start justify-between gap-3">
                <div>
                  <div className="flex items-center gap-2 mb-2">
                    <span className="w-2 h-2 rounded-full" style={{ backgroundColor: getCategoryColor(course.categoryId) }} />
                    <span className="text-xs text-gray-500">{getCategoryName(course.categoryId)}</span>
                  </div>
                  <h3 className="font-semibold text-gray-900">{course.title}</h3>
                  <p className="text-sm text-gray-500 mt-1 line-clamp-2">{course.description}</p>
                </div>
                <span className="text-xs px-2 py-1 rounded-full bg-emerald-50 text-emerald-600 whitespace-nowrap">已开设</span>
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div className="rounded-lg bg-gray-50 p-3">
                  <div className="flex items-center gap-1 text-gray-500 text-xs">
                    <Users className="w-4 h-4" /> 学员数
                  </div>
                  <div className="mt-1 font-semibold text-gray-900">{stats.studentCount}</div>
                </div>
                <div className="rounded-lg bg-gray-50 p-3">
                  <div className="flex items-center gap-1 text-gray-500 text-xs">
                    <TrendingUp className="w-4 h-4" /> 平均进度
                  </div>
                  <div className="mt-1 font-semibold text-gray-900">{stats.averageProgress}%</div>
                </div>
                <div className="rounded-lg bg-gray-50 p-3 col-span-2">
                  <div className="flex items-center gap-1 text-gray-500 text-xs">
                    <Award className="w-4 h-4" /> 平均成绩
                  </div>
                  <div className="mt-1 font-semibold text-gray-900">{stats.averageScore} 分</div>
                  <div className="text-xs text-gray-400 mt-1">已完成 {stats.completionCount} 人</div>
                </div>
              </div>

              <div className="rounded-lg border border-amber-100 bg-amber-50/70 p-3">
                <div className="flex items-center gap-2 text-amber-700">
                  <BookOpen className="w-4 h-4" />
                  <span className="text-sm font-medium">教师教学情况</span>
                </div>
                <p className="mt-2 text-sm text-amber-800">{teacher?.name || course.teacher || '待安排'}</p>
                <p className="text-xs text-amber-700/80">{teacher?.email || student?.email || '可继续补充授课信息'}</p>
              </div>
            </div>
          );
        })}
      </div>

      {filteredCourses.length === 0 && (
        <div className="rounded-xl border border-dashed border-gray-200 bg-white p-10 text-center text-gray-500">
          暂无匹配的已开设课程
        </div>
      )}
    </div>
  );
}

// src/pages/admin/Courses.vue
<template>
  <div class="space-y-6">
    <div class="flex items-center justify-between">
      <div>
        <h1 class="text-2xl font-bold text-gray-900">课程管理</h1>
        <p class="text-gray-500 mt-1">管理所有课程信息</p>
      </div>
      <button @click="showCreateModal = true" class="flex items-center gap-2 px-4 py-2.5 bg-blue-500 hover:bg-blue-600 text-white rounded-lg transition-colors text-sm font-medium">
        <Plus class="w-4 h-4" /> 新建课程
      </button>
    </div>

    <div class="flex gap-6">
      <div class="flex-1 space-y-4">
        <div class="flex gap-3">
          <div class="relative flex-1">
            <Search class="w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" />
            <input v-model="searchText" type="text" placeholder="搜索课程名称..." class="w-full pl-10 pr-4 py-2.5 rounded-lg border border-gray-200 focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20 outline-none text-sm" />
          </div>
          <select v-model="filterCategory" class="px-3 py-2.5 rounded-lg border border-gray-200 focus:border-blue-500 outline-none text-sm">
            <option value="">全部分类</option>
            <option v-for="cat in store.categories" :key="cat.id" :value="cat.id">{{ cat.name }}</option>
          </select>
        </div>

        <div class="bg-white rounded-xl border border-gray-100 shadow-sm overflow-hidden">
          <table class="w-full">
            <thead>
              <tr class="bg-gray-50 border-b border-gray-100">
                <th class="text-left px-4 py-3 text-xs font-medium text-gray-500 uppercase">课程名称</th>
                <th class="text-left px-4 py-3 text-xs font-medium text-gray-500 uppercase">分类</th>
                <th class="text-left px-4 py-3 text-xs font-medium text-gray-500 uppercase">教师</th>
                <th class="text-left px-4 py-3 text-xs font-medium text-gray-500 uppercase">状态</th>
                <th class="text-right px-4 py-3 text-xs font-medium text-gray-500 uppercase">操作</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="course in filteredCourses" :key="course.id" class="border-b border-gray-50 hover:bg-gray-50 transition-colors">
                <td class="px-4 py-3">
                  <div class="flex items-center gap-3">
                    <div :class="'w-8 h-8 rounded-lg flex items-center justify-center ' + getCategoryColor(course.categoryId)">
                      <BookOpen class="w-4 h-4 text-white" />
                    </div>
                    <div>
                      <p class="text-sm font-medium text-gray-900">{{ course.title }}</p>
                      <p class="text-xs text-gray-400">{{ course.id }}</p>
                    </div>
                  </div>
                </td>
                <td class="px-4 py-3 text-sm text-gray-600">{{ getCategoryName(course.categoryId) }}</td>
                <td class="px-4 py-3 text-sm text-gray-600">{{ course.teacher }}</td>
                <td class="px-4 py-3">
                  <span :class="`text-xs px-2 py-1 rounded-full ${course.status === 'active' ? 'bg-green-50 text-green-600' : 'bg-gray-100 text-gray-500'}`">
                    {{ course.status === 'active' ? '进行中' : '已结束' }}
                  </span>
                </td>
                <td class="px-4 py-3 text-right">
                  <button @click="handleEdit(course)" class="text-xs text-blue-500 hover:underline mr-3">编辑</button>
                  <button @click="store.deleteCourse(course.id)" class="text-xs text-red-400 hover:underline">删除</button>
                </td>
              </tr>
              <tr v-if="filteredCourses.length === 0">
                <td colspan="5" class="px-4 py-12 text-center text-gray-400">暂无课程数据</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      <div class="w-64 flex-shrink-0">
        <div class="bg-white rounded-xl border border-gray-100 shadow-sm p-4">
          <h3 class="text-sm font-semibold text-gray-800 mb-3">分类统计</h3>
          <div class="space-y-2">
            <div v-for="cat in store.categories" :key="cat.id" class="flex items-center justify-between text-sm">
              <span class="text-gray-600">{{ cat.name }}</span>
              <span class="text-gray-900 font-medium">{{ getCourseCount(cat.id) }}</span>
            </div>
            <div class="border-t border-gray-100 pt-2 flex items-center justify-between text-sm">
              <span class="text-gray-800 font-medium">总计</span>
              <span class="text-gray-900 font-bold">{{ store.courses.length }}</span>
            </div>
          </div>
        </div>
      </div>
    </div>

    <Teleport to="body">
      <div v-if="showCreateModal" class="fixed inset-0 z-50 flex items-center justify-center">
        <div class="absolute inset-0 bg-black/50" @click="showCreateModal = false" />
        <div class="relative bg-white rounded-xl shadow-2xl w-full max-w-lg mx-4 p-6">
          <h3 class="text-lg font-semibold text-gray-900 mb-4">{{ editingCourse ? '编辑课程' : '新建课程' }}</h3>
          <div class="space-y-4">
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-1">课程名称</label>
              <input v-model="form.title" type="text" class="w-full px-3 py-2 rounded-lg border border-gray-200 focus:border-blue-500 outline-none text-sm" />
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-1">课程描述</label>
              <textarea v-model="form.description" rows="2" class="w-full px-3 py-2 rounded-lg border border-gray-200 focus:border-blue-500 outline-none text-sm"></textarea>
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-1">分类</label>
              <select v-model="form.categoryId" class="w-full px-3 py-2 rounded-lg border border-gray-200 focus:border-blue-500 outline-none text-sm">
                <option v-for="cat in store.categories" :key="cat.id" :value="cat.id">{{ cat.name }}</option>
              </select>
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-1">教师</label>
              <select v-model="form.teacher" class="w-full px-3 py-2 rounded-lg border border-gray-200 focus:border-blue-500 outline-none text-sm">
                <option v-for="t in store.teachers" :key="t.id" :value="t.name">{{ t.name }}</option>
              </select>
            </div>
            <div class="flex gap-3 pt-2">
              <button @click="handleSave" class="flex-1 py-2.5 bg-blue-500 hover:bg-blue-600 text-white rounded-lg text-sm font-medium transition-colors">保存</button>
              <button @click="showCreateModal = false" class="flex-1 py-2.5 bg-gray-100 hover:bg-gray-200 text-gray-600 rounded-lg text-sm font-medium transition-colors">取消</button>
            </div>
          </div>
        </div>
      </div>
    </Teleport>
  </div>
</template>
<script setup lang="ts">
import { ref, computed } from 'vue'
import { useAppStore } from '@/stores/app'
import { Plus, Search, BookOpen } from 'lucide-vue-next'

const store = useAppStore()
const searchText = ref('')
const filterCategory = ref('')
const showCreateModal = ref(false)
const editingCourse = ref<any>(null)
const form = ref({ title: '', description: '', categoryId: '', teacher: '' })

const filteredCourses = computed(() => {
  return store.courses.filter((c) => {
    if (searchText.value && !c.title.includes(searchText.value)) return false
    if (filterCategory.value && c.categoryId !== filterCategory.value) return false
    return true
  })
})

const getCategoryName = (id: string) => store.categories.find((c) => c.id === id)?.name || '未分类'
const getCategoryColor = (id: string) => store.categories.find((c) => c.id === id)?.color || 'bg-gray-500'
const getCourseCount = (id: string) => store.courses.filter((c) => c.categoryId === id).length

const handleEdit = (course: any) => {
  editingCourse.value = course
  form.value = { title: course.title, description: course.description, categoryId: course.categoryId, teacher: course.teacher }
  showCreateModal.value = true
}

const handleSave = () => {
  if (editingCourse.value) {
    store.updateCourse(editingCourse.value.id, { title: form.value.title, description: form.value.description, categoryId: form.value.categoryId, teacher: form.value.teacher })
  } else {
    store.addCourse({ id: Date.now().toString(), title: form.value.title, description: form.value.description, categoryId: form.value.categoryId, teacher: form.value.teacher, cover: '', credits: 0, duration: 0, status: 'active', createdAt: new Date().toISOString() })
  }
  showCreateModal.value = false
  editingCourse.value = null
  form.value = { title: '', description: '', categoryId: '', teacher: '' }
}
</script>
